CREATE TABLE [dbo].[dataholding_ADP] (
    [DateTimeStamp]          VARCHAR (50)   NULL,
    [EmployeeID]             VARCHAR (50)   NULL,
    [SSN]                    VARCHAR (50)   NULL,
    [FirstName]              VARCHAR (255)  NULL,
    [MiddleInitial]          VARCHAR (50)   NULL,
    [LastName]               VARCHAR (255)  NULL,
    [HomeAddress1]           VARCHAR (255)  NULL,
    [HomeAddress2]           VARCHAR (255)  NULL,
    [HomeCity]               VARCHAR (50)   NULL,
    [HomeState]              VARCHAR (50)   NULL,
    [HomeZip]                VARCHAR (50)   NULL,
    [HomePhone]              VARCHAR (50)   NULL,
    [Country]                VARCHAR (50)   NULL,
    [DOB]                    DATE           NULL,
    [Gender]                 VARCHAR (50)   NULL,
    [ActionCode]             VARCHAR (50)   NULL,
    [ReasonCode]             VARCHAR (50)   NULL,
    [EffectiveDate]          DATE           NULL,
    [ADPJobCode]             VARCHAR (50)   NULL,
    [ADPBusinessCode]        VARCHAR (50)   NULL,
    [ACCT_CD]                VARCHAR (50)   NULL,
    [FullPartTime]           CHAR (1)       NULL,
    [BenefitType]            CHAR (1)       NULL,
    [SickPlan]               NVARCHAR (50)  NULL,
    [VacationPlan]           NVARCHAR (50)  NULL,
    [PayRate]                DECIMAL (8, 3) NULL,
    [PayGroup]               CHAR (3)       NULL,
    [WorkLocationCode]       VARCHAR (50)   NULL,
    [CompanyJobTitle]        VARCHAR (255)  NULL,
    [Companycode]            VARCHAR (50)   NULL,
    [FedMaritalStatus]       CHAR (1)       NULL,
    [Fedexemptions]          VARCHAR (20)   NULL,
    [SpecialFedTaxStatus]    CHAR (1)       NULL,
    [Federalpercent]         VARCHAR (20)   NULL,
    [Federalamount]          DECIMAL (6, 2) NULL,
    [StateMaritalStatus]     CHAR (1)       NULL,
    [AZFedWithHolding]       DECIMAL (2, 1) NULL,
    [StateCountyTax]         VARCHAR (20)   NULL,
    [Stateexemptions]        VARCHAR (20)   NULL,
    [SpecialStateTaxStatus]  CHAR (1)       NULL,
    [AddlStatepercent]       VARCHAR (20)   NULL,
    [AddlStateAmount]        DECIMAL (8, 2) NULL,
    [Localexemptions]        VARCHAR (20)   NULL,
    [SpecialLocalTaxStatus]  CHAR (1)       NULL,
    [Localpercent]           VARCHAR (20)   NULL,
    [Localamount]            VARCHAR (50)   NULL,
    [WorkLocalityCode]       VARCHAR (50)   NULL,
    [CandidateID]            VARCHAR (50)   NULL,
    [FinancialDatabase]      VARCHAR (50)   NULL,
    [HomeEmailAddress]       VARCHAR (255)  NULL,
    [PersonalMaritalStatus]  VARCHAR (50)   NULL,
    [TransactionID]          NVARCHAR (50)  NULL,
    [DISTransactionID]       NVARCHAR (50)  NOT NULL,
    [DISActivityID]          INT            NULL,
    [Status]                 VARCHAR (50)   NOT NULL,
    [ADPFileName]            VARCHAR (255)  NULL,
    [id]                     INT            IDENTITY (1, 1) NOT NULL,
    [PlacementID]            VARCHAR (50)   NULL,
    [StartDate]              DATETIME       NULL,
    [TerminationDate]        VARCHAR (50)   NULL,
    [BusinessUnitCode]       VARCHAR (50)   NULL,
    [ProductLine]            VARCHAR (20)   NULL,
    [JobCode]                VARCHAR (50)   NULL,
    [ShiftWorked]            VARCHAR (50)   NULL,
    [Billrate]               VARCHAR (50)   NULL,
    [OvertimeBillRate]       VARCHAR (20)   NULL,
    [DoubleTimeBillRate]     VARCHAR (20)   NULL,
    [STBillRateShift2]       VARCHAR (20)   NULL,
    [OTBillRateShift2]       VARCHAR (20)   NULL,
    [DTBillRateShift2]       VARCHAR (20)   NULL,
    [STBillRateShift3]       VARCHAR (20)   NULL,
    [OTBillRateShift3]       VARCHAR (20)   NULL,
    [DTBillRateShift3]       VARCHAR (20)   NULL,
    [FLSAStatus]             VARCHAR (50)   NULL,
    [BillRateUnit]           VARCHAR (50)   NULL,
    [Exemption]              VARCHAR (50)   NULL,
    [CustomerNumber]         VARCHAR (50)   NULL,
    [CompProfessional]       VARCHAR (50)   NULL,
    [UpdateUserID]           VARCHAR (50)   NULL,
    [PrimaryPlacement]       VARCHAR (50)   NULL,
    [OTPayRate]              VARCHAR (20)   NULL,
    [RecruiterLoginID]       VARCHAR (50)   NULL,
    [ESTEndDate]             VARCHAR (50)   NULL,
    [WorkCity]               VARCHAR (50)   NULL,
    [WorkState]              VARCHAR (50)   NULL,
    [WorkZip]                VARCHAR (50)   NULL,
    [Region]                 VARCHAR (50)   NULL,
    [PayRateUnit]            VARCHAR (50)   NULL,
    [VendorID]               VARCHAR (50)   NULL,
    [DTPayRate]              VARCHAR (20)   NULL,
    [User1]                  VARCHAR (255)  NULL,
    [OTPayRateShift2]        VARCHAR (20)   NULL,
    [User2]                  VARCHAR (255)  NULL,
    [DTPayRateShift2]        VARCHAR (20)   NULL,
    [User3]                  VARCHAR (255)  NULL,
    [STPayRateShift3]        VARCHAR (20)   NULL,
    [DeptID]                 VARCHAR (50)   NULL,
    [OTPayRateShift3]        VARCHAR (20)   NULL,
    [DTPayRateShift3]        VARCHAR (20)   NULL,
    [STPayRateShift2]        VARCHAR (20)   NULL,
    [StateMaritalStatus2]    CHAR (1)       NULL,
    [AZFedWithHolding2]      VARCHAR (50)   NULL,
    [StateTaxCode2]          VARCHAR (50)   NULL,
    [StateExemptions2]       VARCHAR (20)   NULL,
    [ResDef]                 VARCHAR (50)   NULL,
    [AddlStatePercent2]      VARCHAR (20)   NULL,
    [AddlStateAmount2]       VARCHAR (20)   NULL,
    [StateCounty]            VARCHAR (50)   NULL,
    [FedDef]                 VARCHAR (50)   NULL,
    [FedWorkDef]             VARCHAR (50)   NULL,
    [System_Updated]         VARCHAR (200)  NULL,
    [TransactionDate]        DATETIME       NULL,
    [PrivateLabel]           VARCHAR (200)  NULL,
    [SourceAPI]              VARCHAR (300)  NULL,
    [TransactionStatus]      VARCHAR (100)  NULL,
    [TransactionPerformedBy] VARCHAR (255)  NULL,
    [CDIJobCode]             VARCHAR (30)   NULL,
    [SpecialStateTaxStatus2] VARCHAR (20)   NULL,
    [StateCountTax2]         VARCHAR (20)   NULL,
    [StateTaxCode]           VARCHAR (50)   NULL,
    [ADPWorkLocation]        VARCHAR (50)   NULL,
    CONSTRAINT [PK_disholding_ADP] PRIMARY KEY CLUSTERED ([id] ASC)
);












GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_dataholding_ADP]
    ON [dbo].[dataholding_ADP]([TransactionID] ASC);

