CREATE TABLE [dbo].[SECONDARYASSIGNMENT_TRANSACTIONACTIVITY] (
    [Transaction_ID]  VARCHAR (50)   NOT NULL,
    [Activity_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [API_ID]          INT            NOT NULL,
    [TransactionDate] DATETIME       NOT NULL,
    [Status]          VARCHAR (50)   NOT NULL,
    [TransactionData] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_SECONDARYASSIGNMENT_TRANSACTIONACTIVITY] PRIMARY KEY CLUSTERED ([Activity_ID] ASC),
    CONSTRAINT [FK_SECONDARYASSIGNMENT_TRANSACTIONACTIVITY_SECONDARYASSIGNMENT_TRANSACTION] FOREIGN KEY ([Transaction_ID]) REFERENCES [dbo].[SECONDARYASSIGNMENT_TRANSACTION] ([Id])
);



